### ISSUE TITLE
Error in train

### ISSUE THREAD

**Issue by chensh1127** [ONground-Korea/unofficial-Instantsplat#1]
hey, you did a nice job.

I wonder before the **train**. what is the structure of my custom datasets?

I run the code:  `python train.py  -s ./data/coser --exp_name ./data/coser/images --white_bg --iterations 1000 --own_data`
the error is :

   assert imgs, 'no images foud at '+root
AssertionError: no images foud at 

and my datasets is:
<img width="349" alt="image" src="https://github.com/user-attachments/assets/93cbc477-66a1-4098-8673-6b99b4d35c22">

looking forward to your reply.

**Comment by ONground-Korea** [comment]
Hi!

To train in "own data" mode, you need a folder containing only jpg, jpeg, or png image files. For example, a folder containing assets/example/*.jpg would become the custom dataset structure.

![image](https://github.com/user-attachments/assets/345f3382-7ae3-4f82-a82f-06083e37fbd7)

In this situation, the train command would be:

`python train.py -s {your path}/assets/example --exp_name just_example --white_bg --iterations 1000 --own_data`

In your case, if only images exist in `./data/coser/images`, it seems that running the command line as follows should work:

`python train.py -s ./data/coser/images --exp_name test --white_bg --iterations 1000 --own_data`

If you've been proceeding normally in this format, consider using an absolute path instead of a relative path for `-s`. Also, if there's no dust3r checkpoint in dust3r/checkpoints/, it may not work. If the checkpoint is in a different location, add the additional option `--dust3r_path {your path}/*.pth`.

Finally, if the video is not being saved, install an additional library by running `pip install av`.

Please let me know if any additional problems occur.

Thanks,
Jisang.
